### ISSUE TITLE
num & den 

### ISSUE THREAD

**Issue by hacker-DOM** [gnosis/dx-react#100]
https://github.com/gnosis/dutch-exchange/blob/2c16c6949c50db168b983b5d8a1ea8d278231884/contracts/DutchExchange.sol#L842
L842 and 843 should have num and den reverse
when I change it it doesn't pass tests

**Comment by josojo** [comment]
excellent catch. Where is the test not passing?

**Comment by josojo** [comment]
Dom covered this one in the newest commit
