### ISSUE TITLE
2 ways tokens can get stuck

### ISSUE THREAD

**Issue by hacker-DOM** [gnosis/dx-react#126]
The two cases that tokens gets stuck (0 auction or price reaching 0) - I will implement solutions to unstuck them. In particular:
- If there's a zero auction, all extraTokens for that auction will go to extraTokens of next auction
- If there's no buyOrder AND price reaches 0, sellVolume + extraTokens will go to next auction

**Comment by W3stside** [comment]
closing as done @dteiml
