### ISSUE TITLE
No one will post a buyOrder if sellvolume is 0

### ISSUE THREAD

**Issue by josojo** [gnosis/dx-react#130]
https://github.com/gnosis/dutch-exchange/blob/e4c4c384250ddd3552c927c465090c1facdb00e7/contracts/DutchExchange.sol#L414

not 100% sure about it. But I do not think that having the code for shifting extraTokens makes sense here. If the sellvolume is 0, then no one will post a buyOrder. Did you want to reference to sellvolume=sellVolumeCurrent[buyToken][sellToken]?

**Comment by josojo** [comment]
covered in pr134

**Comment by W3stside** [comment]
@josojo closing as solved
