### ISSUE TITLE
Remove this in favor of calling lockedTULBalances[user] directly

### ISSUE THREAD

**Issue by W3stside** [gnosis/dx-react#159]
https://github.com/gnosis/dutch-exchange/blob/ce5c559178da5e2c05f7466e85c8dbd592c095ad/contracts/Tokens/TokenTUL.sol#L119

Just wondering why we are adding a getter for a public mapping here - why not just call:
`tokenTUL.lockedTULBalances.call(user)`?

**Comment by josojo** [comment]
yes this can be removed. This function dates back to a time, when we did not know how to retrieve a value from a strut.

**Comment by W3stside** [comment]
@josojo shall I remove it in my Tulip Refactor PR I'm going to push later?
