### ISSUE TITLE
this comment is not correct

### ISSUE THREAD

**Issue by josojo** [gnosis/dx-react#168]
https://github.com/gnosis/dutch-exchange/blob/639f91e39f4a5a2d2ece245ea67413e84a3cbd30/contracts/DutchExchange.sol#L871

the statement is not correct. both auction numerators could be 0, if an attacker waits for 24 hrs. Using this, an attacker could potentially introduce weird prices, ie. den==0. Fortunately, I can not see any attack with that.

**Comment by hacker-DOM** [comment]
Yeah, it comes from the to when we had arbitration across auctions.

**Comment by hacker-DOM** [comment]
*the time
