### ISSUE TITLE
Up-and-down arrows appear with no use

### ISSUE THREAD

**Issue by YoelWolf** [gnosis/dx-react#412]
Pre conditions:
-Using Firefox 
-Being logged at Metamask

Steps to reproduce:
1- Enter both https://dx.dev.gnosisdev.com/ and https://dx.staging.gnosisdev.com/
2- Choose a Token Pair
3- Click on Specify Amount
4- Observe the gap "Est. Amount receiving"

Expected result: 
The gap shows a 0 (zero) until changes are made

Actual result:
The gap shows a 0 (zero) and two arrows heading up and down to its side. These arrows make no change to the amount receiving.

Environment: 
Firefox - Windows 10
![image 2](https://user-images.githubusercontent.com/44403085/47512967-a6f8ab80-d853-11e8-95a6-23651d48d3b8.png)

**Comment by W3stside** [comment]
fixed as per #414
