### ISSUE TITLE
When the user changes his/her name in the App, it doesn't update in the extension

### ISSUE THREAD

**Issue by lvazq** [gnosis/dx-react#415]
Pre conditions:  
-Using Chrome
-Using app and extension of Gnosis Safe linked

Steps to reproduce:  
1.Tap on the menu on the top right corner
2.Select  Edit Safe Name
3. Select the Adress to chance a name
4.Change the name of the address in the app

Expected result:  
The name of the wallet Extension will change

Actual result:  
The name of the wallet doesn't change in extension

Environment:  
Google chrome - Windows 10  

![gv](https://user-images.githubusercontent.com/44371659/47588314-2bbef480-d93c-11e8-9d8e-c9c6686631b0.PNG)
![im](https://user-images.githubusercontent.com/44371659/47588315-2c578b00-d93c-11e8-8435-9c82ba0b3f16.jpg)

**Comment by W3stside** [comment]
@lvazq please be careful where you post issues, this is `dx-react` not `safe`.... closing.
