### ISSUE TITLE
When you tap on the image on "how it works" section (using Coinbase Wallet) you can't see it in fullscreen

### ISSUE THREAD

**Issue by lvazq** [gnosis/dx-react#416]
Pre conditions:
-Using Coinbase

Steps to reproduce:
1- Enter https://dx.staging.gnosisdev.com/
2- Select 'How it works'
3- Tap on the image of what is Slow.trade
4- Observe

Expected result:
The user see the full screen of the image 

Actual result:
The user can see the file code of the image 

Environment:
Android 7.0

![screenshot_20181029-125447](https://user-images.githubusercontent.com/44371659/47663545-0c160f00-db7c-11e8-95e9-a2e848d7b9eb.jpg)

https://drive.google.com/open?id=1dni6qTNFsyo4wW_50zFDLtN7sBw9fxwq
@andre-meyer

**Comment by W3stside** [comment]
fixed in #418
