### ISSUE TITLE
Slow Trade Verification and Terms

### ISSUE THREAD

**Issue by germartinez** [gnosis/dx-react#417]
The checkbox with the text "I have read, understood, and agree to the full Terms and Conditions:" is always disabled (even after scrolling down the text) if the window size is big (screen size). It's only enabled (after scrolling down) if the window is narrower (mobile size).

Here the differences:

![big_screen](https://user-images.githubusercontent.com/6764315/47687597-436ad700-dbe1-11e8-883c-cb5f8f894b6e.PNG)
![small_screen](https://user-images.githubusercontent.com/6764315/47687600-49f94e80-dbe1-11e8-83f6-cd3d479637c0.PNG)

**Comment by W3stside** [comment]
due to unstable and un-deterministic behaviour, this functionality is removed for now in pr #418
