### ISSUE TITLE
Access forbidden on Rinkeby

### ISSUE THREAD

**Issue by damiandragobetzky** [gnosis/dx-react#447]
Describe the bug:
User is unable to access the web on the Rinkeby net 

To reproduce:
1- Go to Metamask.
2- Switch net to Rinkeby. 
3- Enter http://slow-trade.eth/
4- Observe.

Expected result:
User enters the site normally

Actual result:
A screen with the message "Not found" shows in a white screen.

Device: PC
OS: Windows 10 -Google chrome v71.0.3578.98
Net: Rinkeby 

Screen recording:
https://drive.google.com/file/d/18u-NLdki4-rUuwliW7VIQFiE1caczRKf/view

**Comment by W3stside** [comment]
this is really interesting - cannot reproduce
