### ISSUE TITLE
ETH shown instead of WETH

### ISSUE THREAD

**Issue by damiandragobetzky** [gnosis/dx-react#449]
Description:
When changing the receiving token to ETH and the selling token to DAI (or any other token unable to send directly to ETH), the ETH sign won't change unless you switch its place two times. If you don't, the transaction still succeeds but the tokens are sent to WETH without warning the user. 

To reproduce:
1- Go to http://slow-trade.eth/
2- Click on the middle arrows to make ETH the receiving token.
3- Click on left token and choose DAI or RDN.
4- Edit values for transaction.
5- Submit the transaction.
6- Observe.

Expected result:
At first instance, the ETH converts to WETH. 

Actual result:
The token remains as ETH and the transaction succeeds. 

Device: PC
OS: Windows 10 -Google chrome v71.0.3578.98
Net: Mainnet.

https://drive.google.com/open?id=1CI6pBQHSF-HsMevLJiKybTCYQnyPZR3R

**Comment by W3stside** [comment]
Yep, this is normal! :) Closing.
