### ISSUE TITLE
Loading times are higher than usual

### ISSUE THREAD

**Issue by damiandragobetzky** [gnosis/dx-react#450]
Description:
Claiming funds takes too long to load, and it fails after 240 seconds (4 minutes).

To reproduce: 
Pre-condition: Having finished transactions.

1- Go to http://slow-trade.eth/
2- On "My auctions", click on Claim Funds.
3- Claim the received token.
4- Observe.

Expected result:
Metamask asks for confirmation and the claim succeeds after a short load screen.

Actual result:
The claim takes up to 4 minutes to be loaded, and if so, it fails.

Device: PC
OS: Windows 10 - Google chrome v71.0.3578.98
Net: Mainnet.
TX: 0x34babb27ca7d6150a7f8068b5be9dc3e7f9e0e41cf882fb38d34352330990b0c

Capture:
https://drive.google.com/open?id=16TQML8GjuCp4won0msfqOlfc7oYpxGxG
(Video)
http://prntscr.com/m7hnlf
(Screenshot)

**Comment by MicaelaPesado** [comment]
It also takes too long to load in the stage of "verifying and updating user state".
Device: Moto G6 play
Net: Rinkeby
Opera Wallet

**Comment by W3stside** [comment]
Infura node issue, closing
