### ISSUE TITLE
Privacy Policy won't open.

### ISSUE THREAD

**Issue by damiandragobetzky** [gnosis/dx-react#452]
Description:
Privacy policy gets stuck when loading.

To reproduce:
1- Go to http://slow-trade.eth/
2- On the footer, click on "Privacy Policy".
3- Observe.

Expected result:
Privacy policy opens on a new tab for the user to read. 

Actual result:
The site keeps on loading, stays blank.

Device: PC
OS: Windows 10 - Google chrome v71.0.3578.98
Net: Mainnet-Rinkeby

Capture:
https://drive.google.com/open?id=1qAksIaZ7AztUXFSgoI6eneQnBRevoG30

**Comment by MicaelaPesado** [comment]
It´s still happening, and it is a general problem. It can be reproduced in any browser, either on PC or mobile.

**Comment by W3stside** [comment]
Should be fixed in 2.2.0 - closing for now. Please re-open after 2.2.0 release #467
