### ISSUE TITLE
Missing token pair for DAI, GEN and MKR 

### ISSUE THREAD

**Issue by MicaelaPesado** [gnosis/dx-react#468]
Description:
When you click either on  DAI, GEN or MKR tokens to deposit you can't find a receiving token pair.

To reproduce:
1- Go to https://dx.staging.gnosisdev.com/
2- Choose DAI, GEN or MKR token to deposit.
3- Try to choose a receiving token.
4- Observe.

Expected result:
The user can find at least one token pair to recive (WETH).

Actual result:
The user  can't find a receiving token pair.

Device: PC
Browser: Google Chrome with Metamask extension.
Net: Rinkeby

Capture:
https://drive.google.com/open?id=1uu8-GPMgl9f0ObTaXE4z8TzFehgNXCEV

**Comment by W3stside** [comment]
protocol issue - tokens against those selected are not approved, auction index = 0, so not tradable, closing. Please re-open if still happening after 2.2.0 #467
