### ISSUE TITLE
Auctions which includes OMG tokens don't start

### ISSUE THREAD

**Issue by MicaelaPesado** [gnosis/dx-react#470]
Description:
When you submit an auction including OMG tokens, it never starts. 

To reproduce:
1- Go to dx.staging.gnosisdev.com
2- Submit an auction with OMG tokens
3- Observe.

Expected result:
The auction starts and after some hours the user is able to claim their funds.

Actual result:
The auction doesn't start.

Device: PC
OS: Windows 10 - Google chrome v71.0.3578.98 with Metamask extension.
Net: Rinkeby

**Comment by W3stside** [comment]
I believe this is related to the protocol and bots. @anxolin can you comment?

**Comment by W3stside** [comment]
closing for now, please re-open after #467 2.2.0 release if still happening
