### ISSUE TITLE
Add Token Request: GNO (rinkeby)

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dx-react#473]
I wish to add GNO to the Rinkeby token list

Token address: [0xd0dab4e640d95e9e8a47545598c33e31bdb53c7c](https://rinkeby.etherscan.io/address/0xd0dab4e640d95e9e8a47545598c33e31bdb53c7c)
Token image: [link](https://seeklogo.com/images/G/gnosis-gno-logo-C315E05660-seeklogo.com.png)

Token name: Gnosis
Token symbol: GNO
Token decimals: 18

**Comment by W3stside** [comment]
it is on rinkeby.slow.trade, thanks
