### ISSUE TITLE
[RINKEBY] List GRID and CVC test tokens

### ISSUE THREAD

**Issue by anxolin** [gnosis/dx-react#498]
**Only for RINKEBY**

Add GRID and CVC rinkeby test tokens.
One interesting thing about this tokens is that they don't have 18 decimals.

We want to add them to do more tests and be able to review that it doesn't break any part of the app.

**CVC**:
symbol: "CVC",
name: "Civic",
address: "0x67fe0fdf579043de35d9cb2f10c81b63aa8aeef9",
decimals: 8

**GRID**:
symbol: "GRID",
name: "GRID Token",
address: "0xb35e3e3e7a87c2b04dec49a7b5da7c1a23a09e64",
decimals: 12

**Comment by W3stside** [comment]
closed by #501
