### ISSUE TITLE
enforcing closeOppositeAuction

### ISSUE THREAD

**Issue by josojo** [gnosis/dx-react#75]
https://github.com/gnosis/dutch-exchange/blob/cbc4da2b8fd0a506d6e1e0820bf5e9c6a906eb65/contracts/DutchExchange.sol#L400

currently, if I have an overbuy>=0 I do not have to close the opposite auction. We should enforce the logic of closing the opposite auction even if we have an overbuy>=0.

**Comment by hacker-DOM** [comment]
also correct :)

**Comment by hacker-DOM** [comment]
actually, I don't think this is correct. 
we want to do arbitration if both auctions are running after 6 hrs. If overbuy >=0, we must clear the auction, so the condition won't hold

**Comment by hacker-DOM** [comment]
unless we want to prefer arbitration over the buyer's order. but I think orders should come first.

**Comment by josojo** [comment]
right...
please look at the postbuyOrder of my newest commit in contracts/features/NewSoliditycodeFromDOM, I rearranged it meaningful.
