### ISSUE TITLE
fees are paid for the overbuy

### ISSUE THREAD

**Issue by josojo** [gnosis/dx-react#80]
https://github.com/gnosis/dutch-exchange/blob/eb05f60416a19b8c8d954fd4b50776ecfdca500e/contracts/DutchExchange.sol#L385

in the current logic, I need to pay fees for the total amount and then later the amount gets reduced. That way I am getting charged too much.

proposed fix -> do not calculate any fees if overbuy is greater than 0, because gas costs are high for closing an auction anyway

**Comment by hacker-DOM** [comment]
true
have you done the gas tests with the latest version? What's the difference in closing an auction?
